### ISSUE TITLE
getPane not a function

### ISSUE THREAD

**Issue by DecSander** [IvanSanchez/Leaflet.ImageOverlay.Rotated#5]
Hi, I'm having an issue where when I try to add the rotated image to the map, I get `this.getPane is not a function` 

I'm guessing this is an issue with how i'm using the library but any help would be very much appreciated (I seem to not have this issue when using regular imageOverlay). 

Also, lmk if there's any info I can give that would be more helpful. Thanks!

Also here's how we use it:
```
      let url = target_img.imageUrl;
      let topLeft = latLngToLeaflet(target_img.topLeft);
      let topRight = latLngToLeaflet(target_img.topRight);
      let bottomLeft = latLngToLeaflet(target_img.bottomLeft);
      let bottomRight = latLngToLeaflet(target_img.bottomRight);
      let overlay = Leaflet.imageOverlay.rotated(url, topLeft, topRight, bottomRight).addTo(map);
```
where latLngToLeaflet creates a Leaflet LatLng Object and map is the Leaflet Map Object

Also I'm using v0.1.1 with leaflet 0.7.7

**Comment by DecSander** [comment]
Also I'm using v0.1.1 with leaflet 0.7.7

**Comment by DecSander** [comment]
Nvr mind, just saw the note about it not working with leaflet 0.7, thanks
